title: Alexandra
description: Kurssin teht채v채t
theme: jekyll-theme-architect

header_pages:
  - vko1.html    # tai vko1.md, jos k채yt채t md-versiota
  - vko3.md
  - vko4.md
  - vko5.md
  - vko6.md
  - harjoitustyo.md

